### ISSUE TITLE
[crawler] Add list of users

### ISSUE THREAD

**Issue by tacman** [survos/survos#1]
Currently CrawlCommand gets ALL users in the data and crawls the site.  Better would be if the users were listed in the survos_crawler.yaml config

        $users = $this->crawlerService->getUsers();

```yaml
survos_crawler:
  base_url: https://127.0.0.1:8001/
  users:
     - visitor@mysite.com
     - admin@mysite.com
  login_path: /en/login
  username_form_variable: _username
  password_form_variable: _password
  plaintext_password: kitten
  submit_button: "login_button"
 ```

The command should throw an error if the users don't exist.  If there are no users, it should simply browse the site without login.
