### ISSUE TITLE
[api-grid] Register SlicePaginator without changes services.yaml

### ISSUE THREAD

**Issue by tacman** [survos/survos#4]
We shouldn't have to add the slice paginator in the application services.yamll, we should register it automatically.

```yaml
    # config/services.yaml
    api_platform.doctrine.orm.query_extension.pagination:
        class: Survos\ApiGrid\Paginator\SlicePaginationExtension
        tags:
            - {name : api_platform.doctrine.orm.query_extension.collection, priority: -65}
        autowire: true
```

```php
        $builder->register(SlicePaginationExtension::class)
            ->setAutowired(true)
//            ->addTag('api_platform.doctrine.SlicePaginationExtension.query_extension.collection', ['priority' => -65])
        ;
        $services = $container->services();
        $services->set(SlicePaginationExtension::class)
            ->tag('api_platform.doctrine.SlicePaginationExtension.query_extension.collection', ['priority' => -65])
        $container->services()->alias('api_platform.doctrine.orm.query_extension.pagination', SlicePaginationExtension::class, );
```

To test, go to the anki project

```bash
git pull
bin/import-subtitles.sh day --reset
composer update
```

comment out the wiring in services.yaml, and you can see that it is ignoring the paginator and fetches all the records.
open https://anki.wip/ost/movie/

![image](https://user-images.githubusercontent.com/619585/228504924-1af445be-4c8f-453d-b735-870db8d84e9b.png)

uncomment the section in services.yaml, and it works as expected.

![image](https://user-images.githubusercontent.com/619585/228505673-b2c1014e-4aeb-4a3a-994c-46265d67d429.png)
